### ISSUE TITLE
There is error when start program

### ISSUE THREAD

**Issue by javadev** [konachan700/JNekoImageDB#4]
OS: OSX 10.11.3
Java version: java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
Error message:

Feb 17, 2016 2:42:43 PM jnekoimagesdb.ui.JNekoImageDB start
SEVERE: null
java.io.FileNotFoundException: ./default/public.key (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at jnekoimagesdb.core.img.XImgCrypto.init(XImgCrypto.java:159)
    at jnekoimagesdb.core.img.XImg.init(XImg.java:86)
    at jnekoimagesdb.ui.JNekoImageDB.start(JNekoImageDB.java:145)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
    at com.sun.javafx.application.LauncherImpl$$Lambda$90/1402857099.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl$$Lambda$47/355629945.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$49/2036286154.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$48/1915503092.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Java has been detached already, but someone is still trying to use it at -[GlassRunnable run]:/HUDSON/workspace/8u45-wk/label/macosx-universal-30/rt/modules/graphics/src/main/native-glass/mac/GlassApplication.m:93
Java has been detached already, but someone is still trying to use it at -[GlassRunnable dealloc]:/HUDSON/workspace/8u45-wk/label/macosx-universal-30/rt/modules/graphics/src/main/native-glass/mac/GlassApplication.m:107

**Comment by georgy7** [comment]
@javadev 
Надо установить Java Cryptography Extension (JCE) Unlimited в JRE.
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
Там в README всё написано. В том числе почему оно не идёт в комплекте с JRE.

**Comment by georgy7** [comment]
Ну вообще да, лучше бы показывать сообщение о том, что надо установить JCE, а не падать.

**Comment by konachan700** [comment]
Нет, это не доделано меню выбора баз, и потому папка default (тестовая база) не создается автоматом. Наличие JCE проверяется и если его нет, просто используется меньший ключ, aes-128.

**Comment by javadev** [comment]
Создал каталог `default` - помогло :+1:
